In [1]:
import numpy as np

In [15]:
arr1 = np.array([1,2,3,4,5])

In [16]:
arr1.shape

(5,)

In [17]:
arr2 = np.array([[1,2,3,4,5]])

In [18]:
arr2.shape

(1, 5)

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr1.ndim

1

In [21]:
arr2.ndim

2

In [22]:
arr3 = np.array([1,2,3,4,5,6], dtype=np.float)

In [23]:
arr3.dtype

dtype('float64')

In [4]:
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr5 = np.arange(0,10,1.5)
arr5

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [26]:
arr_random = np.random.random((10,))
arr_random

array([0.14185784, 0.39607384, 0.99096382, 0.59406363, 0.6571876 ,
       0.16565043, 0.71903249, 0.26567349, 0.89106168, 0.92540351])

In [27]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr4_sqrt = np.sqrt(arr4)
arr4_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [29]:
np.sin(arr4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [30]:
arr6 = np.arange(10,20)
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
arr4 + arr6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
arr4*arr6

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [33]:
arr6**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [34]:
arr6.max()

19

In [35]:
arr6.mean()

14.5

In [36]:
arr6.sum()

145

In [37]:
arr6.std()

2.8722813232690143

In [38]:
arr6 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
# create array 1-dim through arange method and check ndim, shape, find the root of std

In [39]:
arr7 = np.arange(20,30)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [42]:
arr7.ndim

1

In [43]:
arr7.shape

(10,)

In [44]:
np.sqrt(arr7.std())

1.694780612135097

In [45]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.insert(arr4,5,10)

array([ 0,  1,  2,  3,  4, 10,  5,  6,  7,  8,  9])

In [47]:
np.delete(arr4,5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [48]:
arr8 = np.array([1,10,5,33,3])
np.sort(arr8)

array([ 1,  3,  5, 10, 33])

In [49]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr = np.concatenate((arr4,arr6))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
arr[(arr < 5)]

array([0, 1, 2, 3, 4])

In [55]:
#AND - & ; OR - | 

In [58]:
arr4[(arr4<10) & (arr4>5)]

array([6, 7, 8, 9])

In [59]:
arr4[(arr4<6) | (arr4>7)]

array([0, 1, 2, 3, 4, 5, 8, 9])

In [61]:
arr[(arr<3) | (arr>17)]

array([ 0,  1,  2, 18, 19])

In [62]:
arr[(arr<3) & (arr>17)]

array([], dtype=int32)

In [9]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix = np.array([(11,12,13),(1,2,3),(21,22,23)])
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [65]:
matrix.shape

(3, 3)

In [66]:
matrix.ndim

2

In [67]:
matrix.size

9

In [68]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [85]:
np.empty(2)

array([1.58984361e-316, 9.76118064e-313])

In [3]:
np.empty((3,3))

array([[1.06144408e-312, 0.00000000e+000, 1.06395697e+224],
       [2.83496884e-032, 6.82178554e-067, 2.21231432e+160],
       [1.88826714e+185, 3.66194868e-086, 6.13486226e-154]])

In [5]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.empty_like(arr4)

In [7]:
a

array([140,   0,   0,   0,   0,   0, 740,   0,   0,   0])

In [11]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [13]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [14]:
np.dot(matrix1, matrix2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [15]:
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [16]:
np.delete(matrix, 2, axis=0) #axis = 0 - row, axis = 1 - column

array([[11, 12, 13],
       [ 1,  2,  3]])

In [17]:
np.delete(matrix, 2, axis = 1)

array([[11, 12],
       [ 1,  2],
       [21, 22]])

In [18]:
np.mean(matrix1, axis = 0)

array([4., 5., 6.])

In [19]:
np.mean(matrix1, axis = 1)

array([2., 5., 8.])

In [20]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [21]:
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [23]:
matrix[1,2] #2-nd row and 3-rd column

3

In [24]:
matrix[:,1]

array([12,  2, 22])

In [25]:
matrix < 5

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [26]:
matrix[matrix<5]

array([1, 2, 3])

In [27]:
# create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, column
#get values which are bigger than 5

In [2]:
matrix3 = np.array([(12,11,10),(9,8,7),(6,5,4),(3,2,1)])
matrix3

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [3]:
matrix4 =np.array([(10,11,12),(7,8,9),(4,5,6),(1,2,3)])
matrix4

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [4]:
matrix5 = matrix3 + matrix4
matrix5

array([[22, 22, 22],
       [16, 16, 16],
       [10, 10, 10],
       [ 4,  4,  4]])

In [32]:
matrix5[2,]

array([10, 10, 10])

In [35]:
matrix5[:,1]

array([22, 16, 10,  4])

In [5]:
matrix5[matrix5>5]

array([22, 22, 22, 16, 16, 16, 10, 10, 10])